In [2]:
import pandas as pd
import numpy as np # noqa
import matplotlib.pyplot as plt

import dtaidistance as dtai

from dtaidistance import dtw

In [3]:
raw_data = pd.read_csv("/Users/jerryinyang/Code/seqluster/data.csv")
data = raw_data[['x', 'y']].to_numpy()

In [4]:

matrix = dtw.distance_matrix_fast(data)

In [5]:
arr = np.random.rand(10, 1)
arr

array([[0.27583552],
       [0.84766465],
       [0.87227128],
       [0.31423198],
       [0.06575156],
       [0.62611373],
       [0.84974807],
       [0.44459075],
       [0.40266992],
       [0.55350134]])

In [6]:
dtw.distance_matrix(np.atleast_2d(arr))

array([[0.        , 0.57182913, 0.59643576, 0.03839646, 0.21008396,
        0.35027821, 0.57391255, 0.16875523, 0.1268344 , 0.27766581],
       [0.57182913, 0.        , 0.02460663, 0.53343267, 0.78191308,
        0.22155092, 0.00208342, 0.4030739 , 0.44499473, 0.29416331],
       [0.59643576, 0.02460663, 0.        , 0.5580393 , 0.80651972,
        0.24615755, 0.02252321, 0.42768053, 0.46960136, 0.31876995],
       [0.03839646, 0.53343267, 0.5580393 , 0.        , 0.24848042,
        0.31188175, 0.53551609, 0.13035877, 0.08843794, 0.23926936],
       [0.21008396, 0.78191308, 0.80651972, 0.24848042, 0.        ,
        0.56036216, 0.78399651, 0.37883918, 0.33691836, 0.48774977],
       [0.35027821, 0.22155092, 0.24615755, 0.31188175, 0.56036216,
        0.        , 0.22363434, 0.18152298, 0.22344381, 0.07261239],
       [0.57391255, 0.00208342, 0.02252321, 0.53551609, 0.78399651,
        0.22363434, 0.        , 0.40515732, 0.44707815, 0.29624674],
       [0.16875523, 0.4030739 , 0.4276805

In [42]:
A = np.random.randint(0, 9, (10, 2))
B = np.random.randint(0, 9, 10)

# Method 1
A * B[:, np.newaxis]

# Method 2
np.array([A[label] * B[label] for label in range(len(A))])

687 ns ± 2.02 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [56]:
np.array([71.1295263, 55.62708035, 66.8515569, 71.02214688]) - np.array([71.12691664, 55.6040948, 67.09601631, 71.10386273])

array([ 0.00260966,  0.02298555, -0.24445941, -0.08171585])

In [58]:
np.array([71.1295263, 55.62708035, 66.8515569 , 71.02214688]) - np.array([71.1292828, 55.62494667, 66.87436095, 71.02981358])

array([ 0.0002435 ,  0.00213368, -0.02280405, -0.0076667 ])

TypeError: '<' not supported between instances of 'list' and 'int'